import '@/styles/globals.css'
import React from 'react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { GlobalContextProvider } from '@/contexts/globalContext'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>TechHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalContextProvider>
        <Component {...pageProps} />
      </GlobalContextProvider>
    </>
  )  
}
