import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const image = "<Image src='https://media.istockphoto.com/id/1071467916/photo/group-of-young-students-working-on-an-assignment.jpg?s=612x612&w=0&k=20&c=LI91Y0Ygig3j6tKJQEWyCEd_yWXzTfPYXfWzx_3-VN4='/>"
  return (
    <>
      <Head>
        <title>TechHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerMain}>
          <h1>Encontre o melhor bootcamp para você</h1>
          <p>Informações sobre os principais bootcamps em Desenvolvimento Web Full Stack do Brasil em um só lugar.</p>
          <div className={styles.grid}>
            <div className={styles.card}>
                <Link href="/schools">
                <h2 className={inter.className}>
                  Escolas <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                  Encontre instituições que oferecem cursos de tecnologia.
                </p>
              </Link>
            </div>
            <div className={styles.card}>
                <Link href="/courses">
                <h2 className={inter.className}>
                  Cursos <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                  Veja detalhes e avaliações sobre os cursos.
                </p>
              </Link>
            </div>
          </div>
          <h2>Qual tecnologia mais te atrai?</h2>
          <p>React icons</p>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Receba o contato das escolas</h2>
            </div> 
            <div className={styles.card}>
              <h2>Avalie seu curso</h2>
            </div>             
          </div>          
        </div>
      </main>
    </>
  )
}
