import Head from 'next/head'
import { Comfortaa } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const font = Comfortaa({ subsets: ['latin'] })

export default function Home() {

  const image = "<Image src='https://media.istockphoto.com/id/1071467916/photo/group-of-young-students-working-on-an-assignment.jpg?s=612x612&w=0&k=20&c=LI91Y0Ygig3j6tKJQEWyCEd_yWXzTfPYXfWzx_3-VN4='/>"
  return (
    <>
      <Head>
        <title>TechHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerMain}>
          <h1 className={font.className}>Encontre o melhor bootcamp para você</h1>
          <p className={font.className}>Informações sobre os principais bootcamps em Desenvolvimento Web Full Stack do Brasil em um só lugar.</p>
          <div className={styles.grid}>
            <div className={styles.card}>
                <Link href="/schools">
                <h2 className={font.className}>
                  Escolas <span>-&gt;</span>
                </h2>
                <p className={font.className}>
                  Encontre instituições que oferecem cursos de tecnologia.
                </p>
              </Link>
            </div>
            <div className={styles.card}>
              <Link href="/courses">
                <h2 className={font.className}>
                  Cursos <span>-&gt;</span>
                </h2>
                <p className={font.className}>
                  Veja detalhes e avaliações sobre os cursos.
                </p>
              </Link>
            </div>
          </div>
          <h3 className={font.className}>Qual tecnologia mais te atrai?</h3>
          <p>PEGAR IMAGENS DO DB</p>
          <div className={styles.grid}>
            <div className={styles.card}>
              <Link href="/soon">
                <h2 className={font.className}>
                  Receba o contato das escolas <span>-&gt;</span>
                </h2>
              </Link>
            </div> 
            <div className={styles.card}>
              <h2 className={font.className}>
                Avalie seu curso <span>-&gt;</span>
              </h2>
            </div>             
          </div>    
        </div>
        <p className={styles.code}>Dúvidas, sugestões ou atualizações? <Link href="https://www.linkedin.com/in/acdayane/">Contate-nos!</Link></p>
        <p className={styles.code}>Feito com ❤. Dayane Piccoli ©2023.</p>    
      </main>
    </>
  )
}
